export const GEOLOCATION_WEATHER_DATA = 'GEOLOCATION_WEATHER_DATA'

export const EXPAND_FORECAST_DATA_START = 'EXPAND_FORECAST_DATA_START'
export const EXPAND_FORECAST_DATA_SUCCESS = 'EXPAND_FORECAST_DATA_SUCCESS'
export const EXPAND_FORECAST_DATA_ERROR = 'EXPAND_FORECAST_DATA_ERROR'

export const ITEM_LIST_GET_DATA = 'ITEM_LIST_GET_DATA'
export const ITEM_LIST_DELETE_ITEM = 'ITEM_LIST_DELETE_ITEM'

export const SEARCH_ITEM = 'SEARCH_ITEM'
